version: '3'

networks:
  dev_network:
    external: true

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: dev-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yyds1234
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev1234
    networks:
      - dev_network
    ports:
      - 3306:3306
  redis:
    image: redis:7.0.11
    restart: always
    container_name: dev-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./etc/redis:/usr/local/etc/redis
      - ./data/redis:/data
    networks:
      - dev_network
    ports:
      - 6379:6379
  etcd:
    image: 'bitnami/etcd:3.5.9'
    container_name: dev-etcd
    volumes:
      - ./data/etcd:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:7379
    networks:
      - dev_network
    ports:
      - 7379:2379
      - 7380:2380
